spring.application.name=scheduler-server

# JDBC properties
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

# JWT properties
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}